version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestGitSaveProject
  gitServerName: test1
  gitUrl: https://github.com/PoojaAnandGit/TestGitSaveProject
  gitUsername: PoojaAnandGit
  gitBranch: main
